### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by icv1003** [SSR1002/GESPRO_GESTIONTAREAS#23]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by DieegoPeri** [comment]
![](https://cloud.githubusercontent.com/assets/6546265/22403769/d292d962-e621-11e6-915a-a39387803ce0.png)

https://medium.com/@ferrand.d/can-you-and-should-you-use-vector-drawables-a-cheatsheet-32a2e1cc2ecf#.eoek6mlry
