### ISSUE TITLE
Entrega TFG

### ISSUE THREAD

**Issue by icv1003** [SSR1002/GESPRO_GESTIONTAREAS#38]
### A entregar:
- Secretaría:
    - [ ] Memoria en formato impreso.
    - [ ] Cinco discos memoria, anexos, fuentes del proyecto, aplicación, otros recursos (videos, máquinas virtuales, software open source de terceros...) .
    - [ ] Un disco con la memoria y anexos con dos resúmenes del trabajo (español y inglés).
    - [ ] Impresos de solicitud.
- UbuVirtual
    - [ ] Memoria y anexos en asignatura TFG.
    - [ ] Memoria y anexos en comunidad TFG.

**Comment by DieegoPeri** [comment]
### **Impresos**

- [impreso_biblioteca.docx](https://github.com/davidmigloz/go-bees/files/750543/impreso_biblioteca.docx)

- [impreso_entrega_tfg.docx](https://github.com/davidmigloz/go-bees/files/750544/impreso_entrega_tfg.docx)
